server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_management
    username: root
    password: root123

mybatis:
  configuration:
    map-underscore-to-camel-case: true