server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_management
    username: root
    password: root123

mybatis:
  config-location: classpath:/static/mybatis/mybatis-config.xml
  mapper-locations: classpath:/static/mybatis/mapper/*.xml